name: Automated Tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/krypton"

      - run: |
          echo "POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> .env
          echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}" >> .env
          echo "POSTGRES_HOST=${{ vars.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ vars.POSTGRES_PORT }}" >> .env
          echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env
          echo "POSTGRES_PASSWORD=${{ vars.POSTGRES_PASSWORD }}" >> .env.test
          echo "POSTGRES_USER=${{ vars.POSTGRES_USER }}" >> .env.test
          echo "POSTGRES_DB=${{ vars.POSTGRES_DB }}" >> .env.test
          echo "POSTGRES_HOST=${{ vars.POSTGRES_HOST }}" >> .env.test
          echo "POSTGRES_PORT=${{ vars.POSTGRES_PORT }}" >> .env.test
          echo "DATABASE_URL=${{ vars.DATABASE_URL }}" >> .env.test

      - run: npm ci

      - run: npm test
